services:
  imagesentiment:
    build: ./app
      
    image: imagesentiment
    container_name: containersentiment
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BASE_URL: ${BASE_URL}
      

  ui:
    build: ./ui
    container_name: sentiment_ui
    ports:
      - "8501:8501"
    depends_on:
      - imagesentiment
    environment:
      API_URL: http://imagesentiment:8000


  db:
    image: postgres:15
    container_name: sentiment_db
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sentiment_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d sentiment_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
